from controllers.usuario import usuario
from controllers.factura import factura
from controllers.estado import estado
from controllers.tipousuario import tipousuario
from controllers.cuadrilla import cuadrilla
from controllers.usuariocuadrilla import usuariocuadrilla
from controllers.detallefactura import detallefactura
from controllers.producto import producto
from controllers.detalleproforma import detalleproforma
from controllers.proforma import proforma
from controllers.horarioprogramacion import horario_programacion
from controllers.programacion import programacion