from sqlalchemy import Table, Column, CHAR, NVARCHAR, DECIMAL, DateTime
from sqlalchemy.sql.sqltypes import Integer, Text
from conn.db import meta

det_facturas = Table('DET_FACTURA', meta,
    Column('Sucursal', CHAR(3), primary_key=True),
    Column('NoFactura', CHAR(8), primary_key=True),
    Column('Serie', NVARCHAR(50), primary_key=True),
    Column('Tipo', CHAR(2), primary_key=True),
    Column('Modo', CHAR(1), primary_key=True),
    Column('FechaFactura', DateTime, primary_key=True),
    Column('Producto', CHAR(20), primary_key=True),
    Column('UMedida', CHAR(2), nullable=False),
    Column('Cantidad', DECIMAL(22, 6)),
    Column('Bonificacion', DECIMAL(10, 2), nullable=False),
    Column('Financiamiento', DECIMAL(10, 2), nullable=False),
    Column('Precio', DECIMAL(20, 6)),
    Column('Porcen_Descto', DECIMAL(22, 6)),
    Column('Descuento', DECIMAL(20, 6)),
    Column('Iva', DECIMAL(20, 6)),
    Column('Costo', DECIMAL(16, 6), nullable=False),
    Column('Exonerado', DECIMAL(20, 6)),
    Column('Bod_Descargue', CHAR(3), primary_key=True),
    Column('CodPrecio', CHAR(2), nullable=False),
    Column('Registro_Usuario', CHAR(50)),
    Column('Registro_Maquina', CHAR(50)),
    Column('Registro_Fecha', DateTime),
    Column('nombre_producto', NVARCHAR(1000)),
    Column('Tipodesc', CHAR(1)),
    Column('tipofac', CHAR(50), nullable=False),
    Column('Numero', Integer, primary_key=True),
    Column('valor', DECIMAL(20, 6)),
    Column('cod_combo', NVARCHAR(20), primary_key=True),
    Column('orden', Integer, nullable=False),
    Column('indice', Integer, primary_key=True),
    Column('Porcentaje_ComisionLista', DECIMAL(5, 2), nullable=False),
    Column('TipoComponente', CHAR(1), nullable=False),
    Column('Gravado', CHAR(1), nullable=False),
    Column('MedidaCosteo', NVARCHAR(2), nullable=False),
    Column('MedidaMovimiento', NVARCHAR(2), nullable=False),
    Column('CantidadMovimiento', DECIMAL(22, 6)),
    Column('Medida_Bonificacion', NVARCHAR(2), nullable=False),
    Column('Bonificacion_Movimiento', DECIMAL(22, 2), nullable=False),
    Column('saldo', DECIMAL(22, 2), nullable=False),
    Column('PrecioDeLista', DECIMAL(22, 6), nullable=False),
    Column('DescuentoFijo', CHAR(1), nullable=False),
    Column('PrioridadDescuento', Integer, nullable=False),
    Column('TipoServicio', Integer, primary_key=True),
    Column('Cupones', Integer, nullable=False),
    Column('Lote', NVARCHAR(100), nullable=False),
    Column('Vencimiento', DateTime, nullable=False),
    Column('Receta', NVARCHAR(1), nullable=False),
    Column('Ruta', Integer, nullable=False),
    Column('IdProgramacion', Integer, nullable=False),
    Column('RegistroFechaApp', DateTime, nullable=False),
    Column('num_parte', NVARCHAR(500), nullable=False),
    Column('OrdenServicio', Text, nullable=False),
    Column('CentroCosto2', Integer, nullable=False),
    Column('CentroCosto3', Integer, nullable=False),
    Column('Impuesto1', DECIMAL(22, 6)),
    Column('Impuesto2', DECIMAL(22, 6)),
    Column('Impuesto3', DECIMAL(22, 6)),
    Column('Impuesto4', DECIMAL(22, 6)),
    Column('Impuesto5', DECIMAL(22, 6)),
    Column('ProductoConsignado', CHAR(1), nullable=False),
    Column('NumeroTrasladoConsignado', NVARCHAR(8), nullable=False)
)