from sqlalchemy import Table, Column, CHAR, NVARCHAR, DECIMAL, DateTime, Numeric
from sqlalchemy.sql.sqltypes import Integer, String
from conn.db import meta

facturas = Table('FACTURA', meta,
    Column('NoFactura', CHAR(8), primary_key=True),
    Column('Serie', NVARCHAR(50), nullable=False),
    Column('Tipo', CHAR(2), nullable=False),
    Column('Modo', CHAR(1), nullable=False),
    Column('FechaFactura', DateTime, nullable=False),
    Column('Moneda', CHAR(1), nullable=False),
    Column('Efectivo', DECIMAL(10, 2), nullable=False),
    Column('Tarjeta', DECIMAL(10, 2), nullable=False),
    Column('Cheque', DECIMAL(10, 2), nullable=False),
    Column('RetencionIR', DECIMAL(22, 6)),
    Column('RetencionALMA', DECIMAL(22, 6)),
    Column('SubTotal', DECIMAL(22, 6)),
    Column('Descuento', DECIMAL(22, 6)),
    Column('Iva', DECIMAL(22, 6)),
    Column('MontoExonerado', DECIMAL(10, 2), nullable=False),
    Column('TotalPago', DECIMAL(22, 6)),
    Column('CodListaPrecio', CHAR(2), nullable=False),
    Column('Sucursal', CHAR(3), nullable=False),
    Column('CodCli', CHAR(6), nullable=False),
    Column('Nombrede', NVARCHAR(200), nullable=False),
    Column('Ruta', CHAR(3), nullable=False),
    Column('Rutero', CHAR(3), nullable=False),
    Column('CentroVenta', CHAR(3), nullable=False),
    Column('Supervisor', CHAR(3), nullable=False),
    Column('Colector', CHAR(3), nullable=False),
    Column('Anulado', CHAR(1), nullable=False),
    Column('valtas', DECIMAL(8, 4), nullable=False),
    Column('Fecha_Vence', DateTime, nullable=False),
    Column('RegistroFecha', DateTime, nullable=False),
    Column('RegistroUsuario', NVARCHAR(50), nullable=False),
    Column('RegistroMaquina', NVARCHAR(50), nullable=False),
    Column('Exonerado', CHAR(1), nullable=False),
    Column('ReferenciaExoneracion', NVARCHAR(50), nullable=False),
    Column('Consignatario', CHAR(1), nullable=False),
    Column('Plazo', DECIMAL(10, 2), nullable=False),
    Column('FormaPago', CHAR(1), nullable=False),
    Column('MontoPrima', DECIMAL(10, 2), nullable=False),
    Column('FechaPagoPrima', DateTime, nullable=False),
    Column('Cuotas', Integer, nullable=False),
    Column('Financiamiento', DECIMAL(10, 2), nullable=False),
    Column('TipoCasa', CHAR(1), nullable=False),
    Column('TiempoResidir', NVARCHAR(30), nullable=False),
    Column('CodTipoCliente', NVARCHAR(3), nullable=False),
    Column('NoIdentificacion', NVARCHAR(40), nullable=False),
    Column('clientecontado', NVARCHAR(200), nullable=False),
    Column('revertida', NVARCHAR(1), nullable=False),
    Column('NumOrden', NVARCHAR(20), nullable=False),
    Column('numprecierre', String(10), nullable=False),
    Column('imprimir', String(1), nullable=False),
    Column('numero', Integer, nullable=False),
    Column('conteo', Integer, nullable=False),
    Column('noapartado', NVARCHAR(8), nullable=False),
    Column('caja', NVARCHAR(3), nullable=False),
    Column('numcierre', NVARCHAR(8)),
    Column('NoRecerva', NVARCHAR(8), nullable=False),
    Column('Version', NVARCHAR(100), nullable=False),
    Column('NoTransaccionInv', Integer, nullable=False),
    Column('CodClienteSucursal', Integer, nullable=False),
    Column('Cajero', NVARCHAR(100), nullable=False),
    Column('Observacion', NVARCHAR(500), nullable=False),
    Column('VerComoPreventa', String(1), nullable=False),
    Column('TipoServicio', Integer, nullable=False),
    Column('Transporte', Numeric(22,2), nullable=False),
    Column('Propina', Numeric(22,2), nullable=False),
    Column('Agente', Integer, nullable=False),
    Column('NombreSubCliente', NVARCHAR(500), nullable=False),
    Column('ClientePadre', NVARCHAR(500), nullable=False),
    Column('NumeroExoneracion', NVARCHAR(600), nullable=False),
    Column('IdentificadorPreventa', Integer, nullable=False),
    Column('ReferenciaPreventa', Integer, nullable=False),
    Column('IdEstado', Integer, nullable=False),
    Column('FechaRetorno', DateTime, nullable=False),
    Column('MotivoRevertida', NVARCHAR, nullable=False),
    Column('HoraRevertida', DateTime, nullable=False),
    Column('HoraEnviado', DateTime, nullable=False),
    Column('CantidadCupones', Integer, nullable=False),
    Column('Referencia', NVARCHAR(100), nullable=False),
    Column('NoPedido', NVARCHAR(10), nullable=False),
    Column('EtiquetaInformativa', NVARCHAR(500), nullable=False),
    Column('Longitud', Numeric(22,6), nullable=False),
    Column('Latitud', Numeric(22,6), nullable=False),
    Column('IdProgramacion', Integer, nullable=False),
    Column('AplicaGarantia', NVARCHAR(1), nullable=False),
    Column('RegistroFechaApp', DateTime, nullable=False),
    Column('Impuesto1', Numeric(22,6)),
    Column('Impuesto2', Numeric(22,6)),
    Column('Impuesto3', Numeric(22,6)),
    Column('Impuesto4', Numeric(22,6)),
    Column('Impuesto5', Numeric(22,6)),
    Column('NumeroTrasladoConsignado', NVARCHAR(8), nullable=False),
    Column('BodDestino', NVARCHAR(3), nullable=False),
    Column('BodDestinoConsignacion', NVARCHAR(3), nullable=False),
    Column('NoConsignacionCLiente', NVARCHAR(8), nullable=False),
    Column('PlanDePago', String(1), nullable=False),
    Column('ROCPRIMA', NVARCHAR(10), nullable=False),
    Column('NoPlanPago', Integer, nullable=False),
    Column('ValorInteres', Numeric(22,2), nullable=False),
    Column('IdPromocion', NVARCHAR, nullable=False),
)
